CREATE USER IF NOT EXISTS 'yourls'@'localhost' IDENTIFIED BY "___DATABASE_PASSWORD___";
CREATE DATABASE IF NOT EXISTS yourls;
GRANT ALL PRIVILEGES ON yourls.* TO 'yourls'@'localhost' IDENTIFIED BY "___DATABASE_PASSWORD___";
FLUSH PRIVILEGES;
QUIT
